/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PLANETFOOD.gui;

import PLANETFOOD.pojo.UserProfile;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class AdminOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionFrame
     */
    public AdminOptionFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
        lblUsername.setText("Hello "+UserProfile.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jrbRemoveEmp = new javax.swing.JRadioButton();
        jrbAddEmp = new javax.swing.JRadioButton();
        jrbViewEmp = new javax.swing.JRadioButton();
        jrbEditEmp = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jrbRegisterCashier = new javax.swing.JRadioButton();
        jrbRemoveCashier = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jrbViewOrder = new javax.swing.JRadioButton();
        jrbViewDateWise = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jrbAddCategory = new javax.swing.JRadioButton();
        jrbEditCategory = new javax.swing.JRadioButton();
        jrbViewCategory = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jrbAddProduct = new javax.swing.JRadioButton();
        jrbRemoveProduct = new javax.swing.JRadioButton();
        jrbViewProduct = new javax.swing.JRadioButton();
        jrbEditProduct = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THE PLANET FOOD APP");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("PLANET FOOD ADMIN PANEL");

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Make A Choice");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true), "Emp Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(240, 240, 240))); // NOI18N

        jrbRemoveEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbRemoveEmp);
        jrbRemoveEmp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbRemoveEmp.setForeground(new java.awt.Color(240, 240, 240));
        jrbRemoveEmp.setText("Remove Emp");

        jrbAddEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbAddEmp);
        jrbAddEmp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbAddEmp.setForeground(new java.awt.Color(240, 240, 240));
        jrbAddEmp.setText("Add Emp");

        jrbViewEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbViewEmp);
        jrbViewEmp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbViewEmp.setForeground(new java.awt.Color(240, 240, 240));
        jrbViewEmp.setText("View Emp");

        jrbEditEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbEditEmp);
        jrbEditEmp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbEditEmp.setForeground(new java.awt.Color(240, 240, 240));
        jrbEditEmp.setText("Edit Emp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbEditEmp)
                    .addComponent(jrbViewEmp)
                    .addComponent(jrbAddEmp)
                    .addComponent(jrbRemoveEmp))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jrbAddEmp)
                .addGap(18, 18, 18)
                .addComponent(jrbViewEmp)
                .addGap(26, 26, 26)
                .addComponent(jrbEditEmp)
                .addGap(18, 18, 18)
                .addComponent(jrbRemoveEmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true), "Cashier Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(240, 240, 240))); // NOI18N

        jrbRegisterCashier.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbRegisterCashier);
        jrbRegisterCashier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbRegisterCashier.setForeground(new java.awt.Color(240, 240, 240));
        jrbRegisterCashier.setText("Register Cashier");

        jrbRemoveCashier.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbRemoveCashier);
        jrbRemoveCashier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbRemoveCashier.setForeground(new java.awt.Color(240, 240, 240));
        jrbRemoveCashier.setText("Remove Cashier");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbRegisterCashier)
                    .addComponent(jrbRemoveCashier))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jrbRegisterCashier)
                .addGap(50, 50, 50)
                .addComponent(jrbRemoveCashier)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true), "Report Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(240, 240, 240))); // NOI18N

        jrbViewOrder.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbViewOrder);
        jrbViewOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbViewOrder.setForeground(new java.awt.Color(240, 240, 240));
        jrbViewOrder.setText("View Orders");

        jrbViewDateWise.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbViewDateWise);
        jrbViewDateWise.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbViewDateWise.setForeground(new java.awt.Color(240, 240, 240));
        jrbViewDateWise.setText("View Date Wise Order");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbViewDateWise)
                    .addComponent(jrbViewOrder))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jrbViewOrder)
                .addGap(46, 46, 46)
                .addComponent(jrbViewDateWise)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true), "Category Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(240, 240, 240))); // NOI18N

        jrbAddCategory.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbAddCategory);
        jrbAddCategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbAddCategory.setForeground(new java.awt.Color(240, 240, 240));
        jrbAddCategory.setText("Add Category");

        jrbEditCategory.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbEditCategory);
        jrbEditCategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbEditCategory.setForeground(new java.awt.Color(240, 240, 240));
        jrbEditCategory.setText("Edit Category");

        jrbViewCategory.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbViewCategory);
        jrbViewCategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbViewCategory.setForeground(new java.awt.Color(240, 240, 240));
        jrbViewCategory.setText("View Category");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbViewCategory)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jrbAddCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jrbEditCategory)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jrbAddCategory)
                .addGap(18, 18, 18)
                .addComponent(jrbEditCategory)
                .addGap(18, 18, 18)
                .addComponent(jrbViewCategory)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true), "Product Option", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(240, 240, 240))); // NOI18N

        jrbAddProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbAddProduct);
        jrbAddProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbAddProduct.setForeground(new java.awt.Color(240, 240, 240));
        jrbAddProduct.setText("Add Product");

        jrbRemoveProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbRemoveProduct);
        jrbRemoveProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbRemoveProduct.setForeground(new java.awt.Color(240, 240, 240));
        jrbRemoveProduct.setText("Remove Product");

        jrbViewProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbViewProduct);
        jrbViewProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbViewProduct.setForeground(new java.awt.Color(240, 240, 240));
        jrbViewProduct.setText("View Product");

        jrbEditProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbEditProduct);
        jrbEditProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbEditProduct.setForeground(new java.awt.Color(240, 240, 240));
        jrbEditProduct.setText("Edit Product");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jrbAddProduct)
                .addGap(35, 35, 35)
                .addComponent(jrbViewProduct)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jrbEditProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbRemoveProduct)
                .addGap(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jrbAddProduct))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jrbViewProduct)))
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbEditProduct)
                    .addComponent(jrbRemoveProduct))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnDoTask.setBackground(new java.awt.Color(0, 153, 153));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(240, 240, 240));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(0, 153, 153));
        btnQuit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(240, 240, 240));
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(240, 240, 240));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(240, 240, 240));
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsernameMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogout)
                        .addGap(40, 40, 40))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblLogout)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDoTask))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnQuit)))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        QuitFrame qf=new QuitFrame();
        qf.setVisible(true);
        
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
      String task=getOption();
      if(task==null)
      {
          JOptionPane.showMessageDialog(null,"Please Choose An Option","Error!",JOptionPane.ERROR_MESSAGE);
          return;
      }
      JFrame jf=null;
          if(task.equals("Add Product"))
          {
              jf=new ProductAddingFrame();
          }
          else if(task.equals("Edit Product"))
          {
              jf=new ProductEditingFrame();
          }
          else if(task.equals("View Product"))
          {
              jf=new ViewProductsFrame();
          }
          else if(task.equals("Remove Product"))
          {
              jf=new ProductRemovingFrame();
          }
          else if(task.equals("Register Cashier"))
          {
              jf=new RegisterCashierFrame();
          }
          else if(task.equals("Remove Cashier"))
          {
              jf=new RemoveCashierFrame();
          }
          else if(task.equals("Add Emp"))
          {
              jf=new AddEmpFrame();
          }
          else if(task.equals("Edit Emp"))
          {
              jf=new EditEmpFrame();
          }
          else if(task.equals("View Emp"))
          {
              jf=new ViewEmpFrame();
          }
          else if(task.equals("Remove Emp"))
          {
              jf=new RemoveEmpFrame();
          }
          else if(task.equals("Add Category"))
          {
              jf=new AddCategoryFrame();
          }
          else if(task.equals("Edit Category"))
          {
              jf=new EditCategoryFrame();
          }
          else if(task.equals("View Category"))
          {
              jf=new ViewAllCategoriesFrame();
          }
          else if(task.equals("View Orders"))
          {
              jf=new ViewAllOrdersFrame();
          }
          else if(task.equals("View Date Wise Order"))
          {
              jf=new ViewAllDateWiseOrdersFrame();
          }
          
          jf.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setForeground(Color.yellow);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        this.dispose();
        LoginFrame loginFrame=new LoginFrame();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setForeground(Color.white);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseExited
        lblUsername.setForeground(Color.white);
    }//GEN-LAST:event_lblUsernameMouseExited

    private void lblUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseEntered
        lblUsername.setForeground(Color.yellow);
    }//GEN-LAST:event_lblUsernameMouseEntered

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked

    }//GEN-LAST:event_lblUsernameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionFrame().setVisible(true);
            }
        });
    }
    private String getOption()
    {
        if(jrbAddEmp.isSelected())
            return jrbAddEmp.getText();
        else if(jrbEditEmp.isSelected())
            return jrbEditEmp.getText();
        else if(jrbRemoveEmp.isSelected())
            return jrbRemoveEmp.getText();
        else if(jrbViewEmp.isSelected())
            return jrbViewEmp.getText();
        else if(jrbViewOrder.isSelected())
            return jrbViewOrder.getText();
        else if(jrbViewDateWise.isSelected())
            return jrbViewDateWise.getText();
        if(jrbAddProduct.isSelected())
            return jrbAddProduct.getText();
        else if(jrbEditProduct.isSelected())
            return jrbEditProduct.getText();
        else if(jrbRemoveProduct.isSelected())
            return jrbRemoveProduct.getText();
        else if(jrbViewProduct.isSelected())
            return jrbViewProduct.getText();
        else if(jrbRegisterCashier.isSelected())
            return jrbRegisterCashier.getText();
        else if(jrbRemoveCashier.isSelected())
            return jrbRemoveCashier.getText();
        else if(jrbRegisterCashier.isSelected())
            return jrbRegisterCashier.getText();
        else if(jrbAddCategory.isSelected())
            return jrbAddCategory.getText();
        else if(jrbEditCategory.isSelected())
            return jrbEditCategory.getText();
        else if(jrbViewCategory.isSelected())
            return jrbViewCategory.getText();
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.JButton btnQuit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jrbAddCategory;
    private javax.swing.JRadioButton jrbAddEmp;
    private javax.swing.JRadioButton jrbAddProduct;
    private javax.swing.JRadioButton jrbEditCategory;
    private javax.swing.JRadioButton jrbEditEmp;
    private javax.swing.JRadioButton jrbEditProduct;
    private javax.swing.JRadioButton jrbRegisterCashier;
    private javax.swing.JRadioButton jrbRemoveCashier;
    private javax.swing.JRadioButton jrbRemoveEmp;
    private javax.swing.JRadioButton jrbRemoveProduct;
    private javax.swing.JRadioButton jrbViewCategory;
    private javax.swing.JRadioButton jrbViewDateWise;
    private javax.swing.JRadioButton jrbViewEmp;
    private javax.swing.JRadioButton jrbViewOrder;
    private javax.swing.JRadioButton jrbViewProduct;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
